"""add estacion_usuario table and fix relations

Revision ID: a5dbd1dd5bc9
Revises: ee1e6c6cbc88
Create Date: 2026-07-25 21:26:04.438173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5dbd1dd5bc9'
down_revision: Union[str, Sequence[str], None] = 'ee1e6c6cbc88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estacion_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('estacion_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('fecha_union', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['estacion_id'], ['estacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'estacion_id', name='uq_user_estacion')
    )
    op.create_index(op.f('ix_estacion_usuario_estacion_id'), 'estacion_usuario', ['estacion_id'], unique=False)
    op.create_index(op.f('ix_estacion_usuario_id'), 'estacion_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_estacion_usuario_user_id'), 'estacion_usuario', ['user_id'], unique=False)
    op.add_column('estacion', sa.Column('max_usuarios', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estacion', 'max_usuarios')
    op.drop_index(op.f('ix_estacion_usuario_user_id'), table_name='estacion_usuario')
    op.drop_index(op.f('ix_estacion_usuario_id'), table_name='estacion_usuario')
    op.drop_index(op.f('ix_estacion_usuario_estacion_id'), table_name='estacion_usuario')
    op.drop_table('estacion_usuario')
    # ### end Alembic commands ###
