"""initial

Revision ID: ee1e6c6cbc88
Revises: 
Create Date: 2026-03-15 11:23:31.395146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1e6c6cbc88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('client', 'admin', 'superadmin', name='userrole'), nullable=False),
    sa.Column('activity', sa.String(length=100), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('public_station_access', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('estacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estacion_codigo'), 'estacion', ['codigo'], unique=True)
    op.create_index(op.f('ix_estacion_id'), 'estacion', ['id'], unique=False)
    op.create_table('datos_sensores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('humedad', sa.Float(), nullable=True),
    sa.Column('lluvia', sa.Float(), nullable=True),
    sa.Column('velocidad_viento', sa.Float(), nullable=True),
    sa.Column('direccion_viento', sa.Float(), nullable=True),
    sa.Column('rafaga_viento', sa.Float(), nullable=True),
    sa.Column('presion_barometrica', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['estacion.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datos_sensores_fecha'), 'datos_sensores', ['fecha'], unique=False)
    op.create_index(op.f('ix_datos_sensores_id'), 'datos_sensores', ['id'], unique=False)
    op.create_index(op.f('ix_datos_sensores_sensor_id'), 'datos_sensores', ['sensor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datos_sensores_sensor_id'), table_name='datos_sensores')
    op.drop_index(op.f('ix_datos_sensores_id'), table_name='datos_sensores')
    op.drop_index(op.f('ix_datos_sensores_fecha'), table_name='datos_sensores')
    op.drop_table('datos_sensores')
    op.drop_index(op.f('ix_estacion_id'), table_name='estacion')
    op.drop_index(op.f('ix_estacion_codigo'), table_name='estacion')
    op.drop_table('estacion')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
